'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("250, 250")>  _
        Public Property MainFormLocation() As Global.System.Drawing.Point
            Get
                Return CType(Me("MainFormLocation"),Global.System.Drawing.Point)
            End Get
            Set
                Me("MainFormLocation") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property TimesRun() As Long
            Get
                Return CType(Me("TimesRun"),Long)
            End Get
            Set
                Me("TimesRun") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property MustUpgrade() As Boolean
            Get
                Return CType(Me("MustUpgrade"),Boolean)
            End Get
            Set
                Me("MustUpgrade") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ApiKey() As String
            Get
                Return CType(Me("ApiKey"),String)
            End Get
            Set
                Me("ApiKey") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("35")>  _
        Public Property cLatitude() As Single
            Get
                Return CType(Me("cLatitude"),Single)
            End Get
            Set
                Me("cLatitude") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("-78")>  _
        Public Property cLongitude() As Single
            Get
                Return CType(Me("cLongitude"),Single)
            End Get
            Set
                Me("cLongitude") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("15")>  _
        Public Property UpdateInterval() As Integer
            Get
                Return CType(Me("UpdateInterval"),Integer)
            End Get
            Set
                Me("UpdateInterval") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Daily_Temp() As Boolean
            Get
                Return CType(Me("Daily_Temp"),Boolean)
            End Get
            Set
                Me("Daily_Temp") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Daily_FeelsLike() As Boolean
            Get
                Return CType(Me("Daily_FeelsLike"),Boolean)
            End Get
            Set
                Me("Daily_FeelsLike") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Daily_Dewpoint() As Boolean
            Get
                Return CType(Me("Daily_Dewpoint"),Boolean)
            End Get
            Set
                Me("Daily_Dewpoint") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Daily_Humidity() As Boolean
            Get
                Return CType(Me("Daily_Humidity"),Boolean)
            End Get
            Set
                Me("Daily_Humidity") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Daily_WindSpeed() As Boolean
            Get
                Return CType(Me("Daily_WindSpeed"),Boolean)
            End Get
            Set
                Me("Daily_WindSpeed") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Daily_WindDir() As Boolean
            Get
                Return CType(Me("Daily_WindDir"),Boolean)
            End Get
            Set
                Me("Daily_WindDir") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Daily_Bp() As Boolean
            Get
                Return CType(Me("Daily_Bp"),Boolean)
            End Get
            Set
                Me("Daily_Bp") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Daily_Precip() As Boolean
            Get
                Return CType(Me("Daily_Precip"),Boolean)
            End Get
            Set
                Me("Daily_Precip") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Daily_PrecipProb() As Boolean
            Get
                Return CType(Me("Daily_PrecipProb"),Boolean)
            End Get
            Set
                Me("Daily_PrecipProb") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Daily_PrecipAcc() As Boolean
            Get
                Return CType(Me("Daily_PrecipAcc"),Boolean)
            End Get
            Set
                Me("Daily_PrecipAcc") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Daily_Sunrise() As Boolean
            Get
                Return CType(Me("Daily_Sunrise"),Boolean)
            End Get
            Set
                Me("Daily_Sunrise") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Daily_Sunset() As Boolean
            Get
                Return CType(Me("Daily_Sunset"),Boolean)
            End Get
            Set
                Me("Daily_Sunset") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Daily_Vis() As Boolean
            Get
                Return CType(Me("Daily_Vis"),Boolean)
            End Get
            Set
                Me("Daily_Vis") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Daily_WxCode() As Boolean
            Get
                Return CType(Me("Daily_WxCode"),Boolean)
            End Get
            Set
                Me("Daily_WxCode") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Daily_MoonPhase() As Boolean
            Get
                Return CType(Me("Daily_MoonPhase"),Boolean)
            End Get
            Set
                Me("Daily_MoonPhase") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property Units() As Integer
            Get
                Return CType(Me("Units"),Integer)
            End Get
            Set
                Me("Units") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Hour_Temp() As Boolean
            Get
                Return CType(Me("Hour_Temp"),Boolean)
            End Get
            Set
                Me("Hour_Temp") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Hour_FeelsLike() As Boolean
            Get
                Return CType(Me("Hour_FeelsLike"),Boolean)
            End Get
            Set
                Me("Hour_FeelsLike") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Hour_Dewpoint() As Boolean
            Get
                Return CType(Me("Hour_Dewpoint"),Boolean)
            End Get
            Set
                Me("Hour_Dewpoint") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Hour_Humidity() As Boolean
            Get
                Return CType(Me("Hour_Humidity"),Boolean)
            End Get
            Set
                Me("Hour_Humidity") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Hour_WindSpeed() As Boolean
            Get
                Return CType(Me("Hour_WindSpeed"),Boolean)
            End Get
            Set
                Me("Hour_WindSpeed") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Hour_WindDir() As Boolean
            Get
                Return CType(Me("Hour_WindDir"),Boolean)
            End Get
            Set
                Me("Hour_WindDir") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Hour_WindGust() As Boolean
            Get
                Return CType(Me("Hour_WindGust"),Boolean)
            End Get
            Set
                Me("Hour_WindGust") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Hour_Bp() As Boolean
            Get
                Return CType(Me("Hour_Bp"),Boolean)
            End Get
            Set
                Me("Hour_Bp") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Hour_Precip() As Boolean
            Get
                Return CType(Me("Hour_Precip"),Boolean)
            End Get
            Set
                Me("Hour_Precip") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Hour_PrecipType() As Boolean
            Get
                Return CType(Me("Hour_PrecipType"),Boolean)
            End Get
            Set
                Me("Hour_PrecipType") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Hour_PrecipProb() As Boolean
            Get
                Return CType(Me("Hour_PrecipProb"),Boolean)
            End Get
            Set
                Me("Hour_PrecipProb") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Hour_Sunrise() As Boolean
            Get
                Return CType(Me("Hour_Sunrise"),Boolean)
            End Get
            Set
                Me("Hour_Sunrise") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Hour_Sunset() As Boolean
            Get
                Return CType(Me("Hour_Sunset"),Boolean)
            End Get
            Set
                Me("Hour_Sunset") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Hour_Vis() As Boolean
            Get
                Return CType(Me("Hour_Vis"),Boolean)
            End Get
            Set
                Me("Hour_Vis") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Hour_CloudCover() As Boolean
            Get
                Return CType(Me("Hour_CloudCover"),Boolean)
            End Get
            Set
                Me("Hour_CloudCover") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Hour_CloudBase() As Boolean
            Get
                Return CType(Me("Hour_CloudBase"),Boolean)
            End Get
            Set
                Me("Hour_CloudBase") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Hour_CloudCeil() As Boolean
            Get
                Return CType(Me("Hour_CloudCeil"),Boolean)
            End Get
            Set
                Me("Hour_CloudCeil") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Hour_SSR() As Boolean
            Get
                Return CType(Me("Hour_SSR"),Boolean)
            End Get
            Set
                Me("Hour_SSR") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Hour_MoonPhase() As Boolean
            Get
                Return CType(Me("Hour_MoonPhase"),Boolean)
            End Get
            Set
                Me("Hour_MoonPhase") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Hour_WxCode() As Boolean
            Get
                Return CType(Me("Hour_WxCode"),Boolean)
            End Get
            Set
                Me("Hour_WxCode") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Hour_TreePollen() As Boolean
            Get
                Return CType(Me("Hour_TreePollen"),Boolean)
            End Get
            Set
                Me("Hour_TreePollen") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Hour_WeedPollen() As Boolean
            Get
                Return CType(Me("Hour_WeedPollen"),Boolean)
            End Get
            Set
                Me("Hour_WeedPollen") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Hour_GrassPollen() As Boolean
            Get
                Return CType(Me("Hour_GrassPollen"),Boolean)
            End Get
            Set
                Me("Hour_GrassPollen") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Hour_TreeAcacia() As Boolean
            Get
                Return CType(Me("Hour_TreeAcacia"),Boolean)
            End Get
            Set
                Me("Hour_TreeAcacia") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Hour_TreeAsh() As Boolean
            Get
                Return CType(Me("Hour_TreeAsh"),Boolean)
            End Get
            Set
                Me("Hour_TreeAsh") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Hour_TreeBeech() As Boolean
            Get
                Return CType(Me("Hour_TreeBeech"),Boolean)
            End Get
            Set
                Me("Hour_TreeBeech") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Hour_TreeBirch() As Boolean
            Get
                Return CType(Me("Hour_TreeBirch"),Boolean)
            End Get
            Set
                Me("Hour_TreeBirch") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Hour_TreeCedar() As Boolean
            Get
                Return CType(Me("Hour_TreeCedar"),Boolean)
            End Get
            Set
                Me("Hour_TreeCedar") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Hour_TreeCottonwood() As Boolean
            Get
                Return CType(Me("Hour_TreeCottonwood"),Boolean)
            End Get
            Set
                Me("Hour_TreeCottonwood") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Hour_TreeCypress() As Boolean
            Get
                Return CType(Me("Hour_TreeCypress"),Boolean)
            End Get
            Set
                Me("Hour_TreeCypress") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Hour_TreeElder() As Boolean
            Get
                Return CType(Me("Hour_TreeElder"),Boolean)
            End Get
            Set
                Me("Hour_TreeElder") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Hour_TreeElm() As Boolean
            Get
                Return CType(Me("Hour_TreeElm"),Boolean)
            End Get
            Set
                Me("Hour_TreeElm") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Hour_Grass() As Boolean
            Get
                Return CType(Me("Hour_Grass"),Boolean)
            End Get
            Set
                Me("Hour_Grass") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Hour_TreeHemlock() As Boolean
            Get
                Return CType(Me("Hour_TreeHemlock"),Boolean)
            End Get
            Set
                Me("Hour_TreeHemlock") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Hour_TreeHickory() As Boolean
            Get
                Return CType(Me("Hour_TreeHickory"),Boolean)
            End Get
            Set
                Me("Hour_TreeHickory") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Hour_TreeJuniper() As Boolean
            Get
                Return CType(Me("Hour_TreeJuniper"),Boolean)
            End Get
            Set
                Me("Hour_TreeJuniper") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Hour_TreeMahogany() As Boolean
            Get
                Return CType(Me("Hour_TreeMahogany"),Boolean)
            End Get
            Set
                Me("Hour_TreeMahogany") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Hour_TreeMaple() As Boolean
            Get
                Return CType(Me("Hour_TreeMaple"),Boolean)
            End Get
            Set
                Me("Hour_TreeMaple") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Hour_TreeMulberry() As Boolean
            Get
                Return CType(Me("Hour_TreeMulberry"),Boolean)
            End Get
            Set
                Me("Hour_TreeMulberry") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Hour_TreePine() As Boolean
            Get
                Return CType(Me("Hour_TreePine"),Boolean)
            End Get
            Set
                Me("Hour_TreePine") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Hour_Ragweed() As Boolean
            Get
                Return CType(Me("Hour_Ragweed"),Boolean)
            End Get
            Set
                Me("Hour_Ragweed") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Hour_TreeSpruce() As Boolean
            Get
                Return CType(Me("Hour_TreeSpruce"),Boolean)
            End Get
            Set
                Me("Hour_TreeSpruce") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Hour_TreeSycamore() As Boolean
            Get
                Return CType(Me("Hour_TreeSycamore"),Boolean)
            End Get
            Set
                Me("Hour_TreeSycamore") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Hour_TreeWalnut() As Boolean
            Get
                Return CType(Me("Hour_TreeWalnut"),Boolean)
            End Get
            Set
                Me("Hour_TreeWalnut") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Hour_TreeWillow() As Boolean
            Get
                Return CType(Me("Hour_TreeWillow"),Boolean)
            End Get
            Set
                Me("Hour_TreeWillow") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Hour_TreeOak() As Boolean
            Get
                Return CType(Me("Hour_TreeOak"),Boolean)
            End Get
            Set
                Me("Hour_TreeOak") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Hour_Pm10() As Boolean
            Get
                Return CType(Me("Hour_Pm10"),Boolean)
            End Get
            Set
                Me("Hour_Pm10") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Hour_Pm25() As Boolean
            Get
                Return CType(Me("Hour_Pm25"),Boolean)
            End Get
            Set
                Me("Hour_Pm25") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Hour_O3() As Boolean
            Get
                Return CType(Me("Hour_O3"),Boolean)
            End Get
            Set
                Me("Hour_O3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Hour_No2() As Boolean
            Get
                Return CType(Me("Hour_No2"),Boolean)
            End Get
            Set
                Me("Hour_No2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Hour_Co() As Boolean
            Get
                Return CType(Me("Hour_Co"),Boolean)
            End Get
            Set
                Me("Hour_Co") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Hour_So2() As Boolean
            Get
                Return CType(Me("Hour_So2"),Boolean)
            End Get
            Set
                Me("Hour_So2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Hour_EpaAqi() As Boolean
            Get
                Return CType(Me("Hour_EpaAqi"),Boolean)
            End Get
            Set
                Me("Hour_EpaAqi") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Hour_EpaHealthConcern() As Boolean
            Get
                Return CType(Me("Hour_EpaHealthConcern"),Boolean)
            End Get
            Set
                Me("Hour_EpaHealthConcern") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Hour_EpaPrimaryPollutant() As Boolean
            Get
                Return CType(Me("Hour_EpaPrimaryPollutant"),Boolean)
            End Get
            Set
                Me("Hour_EpaPrimaryPollutant") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Hour_ChinaAqi() As Boolean
            Get
                Return CType(Me("Hour_ChinaAqi"),Boolean)
            End Get
            Set
                Me("Hour_ChinaAqi") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Hour_ChinaHealthConcern() As Boolean
            Get
                Return CType(Me("Hour_ChinaHealthConcern"),Boolean)
            End Get
            Set
                Me("Hour_ChinaHealthConcern") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Hour_ChinaPrimaryPollutant() As Boolean
            Get
                Return CType(Me("Hour_ChinaPrimaryPollutant"),Boolean)
            End Get
            Set
                Me("Hour_ChinaPrimaryPollutant") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Hour_RoadRisk() As Boolean
            Get
                Return CType(Me("Hour_RoadRisk"),Boolean)
            End Get
            Set
                Me("Hour_RoadRisk") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Hour_RiskScore() As Boolean
            Get
                Return CType(Me("Hour_RiskScore"),Boolean)
            End Get
            Set
                Me("Hour_RiskScore") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Hour_RiskConfidence() As Boolean
            Get
                Return CType(Me("Hour_RiskConfidence"),Boolean)
            End Get
            Set
                Me("Hour_RiskConfidence") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Hour_RiskCondition() As Boolean
            Get
                Return CType(Me("Hour_RiskCondition"),Boolean)
            End Get
            Set
                Me("Hour_RiskCondition") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Hour_HailRisk() As Boolean
            Get
                Return CType(Me("Hour_HailRisk"),Boolean)
            End Get
            Set
                Me("Hour_HailRisk") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Fetch_Daily() As Boolean
            Get
                Return CType(Me("Fetch_Daily"),Boolean)
            End Get
            Set
                Me("Fetch_Daily") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Fetch_Hourly() As Boolean
            Get
                Return CType(Me("Fetch_Hourly"),Boolean)
            End Get
            Set
                Me("Fetch_Hourly") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.ClimaCell.My.MySettings
            Get
                Return Global.ClimaCell.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
