Friend Module SettingsRoutines


    Friend Sub LoadDailySettings()
        With FrmMain
            .ChkBP.Checked = My.Settings.Daily_Bp
            .ChkDewpoint.Checked = My.Settings.Daily_Dewpoint
            .ChkFeelsLike.Checked = My.Settings.Daily_FeelsLike
            .ChkHumidity.Checked = My.Settings.Daily_Humidity
            .ChkPrecip.Checked = My.Settings.Daily_Precip
            .ChkPrecipAcc.Checked = My.Settings.Daily_PrecipAcc
            .ChkPrecipProb.Checked = My.Settings.Daily_PrecipProb
            .ChkSunrise.Checked = My.Settings.Daily_Sunrise
            .ChkSunset.Checked = My.Settings.Daily_Sunset
            .ChkTemp.Checked = My.Settings.Daily_Temp
            .ChkVis.Checked = My.Settings.Daily_Vis
            .ChkWindDir.Checked = My.Settings.Daily_WindDir
            .ChkWindSpeed.Checked = My.Settings.Daily_WindSpeed
            .ChkWxCode.Checked = My.Settings.Daily_WxCode
            .ChkMoonPhase.Checked = My.Settings.Daily_MoonPhase
        End With
    End Sub
    Friend Sub LoadHrSettings()
        With FrmMain
            .ChkHrBP.Checked = My.Settings.Hour_Bp
            .ChkHrDewpoint.Checked = My.Settings.Hour_Dewpoint
            .ChkHrFeelsLike.Checked = My.Settings.Hour_FeelsLike
            .ChkHrRH.Checked = My.Settings.Hour_Humidity
            .ChkHrPrecip.Checked = My.Settings.Hour_Precip
            .ChkHrPrecipType.Checked = My.Settings.Hour_PrecipType
            .ChkHrPrecipProb.Checked = My.Settings.Hour_PrecipProb
            .ChkHrSunrise.Checked = My.Settings.Hour_Sunrise
            .ChkHrSunset.Checked = My.Settings.Hour_Sunset
            .ChkHrTemp.Checked = My.Settings.Hour_Temp
            .ChkHrVis.Checked = My.Settings.Hour_Vis
            .ChkHrWindDir.Checked = My.Settings.Hour_WindDir
            .ChkHrWindSpeed.Checked = My.Settings.Hour_WindSpeed
            .ChkHrWindGust.Checked = My.Settings.Hour_WindGust
            .ChkHrWxCode.Checked = My.Settings.Hour_WxCode
            .ChkHrMoonPhase.Checked = My.Settings.Hour_MoonPhase
            .ChkHrSSR.Checked = My.Settings.Hour_SSR
            .ChkHrCloudBase.Checked = My.Settings.Hour_CloudBase
            .ChkHrCloudCeil.Checked = My.Settings.Hour_CloudCeil
            .ChkHrCloudCover.Checked = My.Settings.Hour_CloudCover
            .ChkHrTreePollen.Checked = My.Settings.Hour_TreePollen
            .ChkHrWeedPollen.Checked = My.Settings.Hour_WeedPollen
            .ChkHrGrassPollen.Checked = My.Settings.Hour_GrassPollen
            .ChkHrTreeAcacia.Checked = My.Settings.Hour_TreeAcacia
            .ChkHrTreeAsh.Checked = My.Settings.Hour_TreeAsh
            .ChkHrTreeBeech.Checked = My.Settings.Hour_TreeBeech
            .ChkHrTreeBirch.Checked = My.Settings.Hour_TreeBirch
            .ChkHrTreeCedar.Checked = My.Settings.Hour_TreeCedar
            .ChkHrTreeCottonwood.Checked = My.Settings.Hour_TreeCottonwood
            .ChkHrTreeCypress.Checked = My.Settings.Hour_TreeCypress
            .ChkHrTreeElder.Checked = My.Settings.Hour_TreeElder
            .ChkHrTreeElm.Checked = My.Settings.Hour_TreeElm
            .ChkHrGrass.Checked = My.Settings.Hour_Grass
            .ChkHrTreeHemlock.Checked = My.Settings.Hour_TreeHemlock
            .ChkHrTreeHickory.Checked = My.Settings.Hour_TreeHickory
            .ChkHrTreeJuniper.Checked = My.Settings.Hour_TreeJuniper
            .ChkHrTreeMahogany.Checked = My.Settings.Hour_TreeMahogany
            .ChkHrTreeMaple.Checked = My.Settings.Hour_TreeMaple
            .ChkHrTreeMulberry.Checked = My.Settings.Hour_TreeMulberry
            .ChkHrTreeOak.Checked = My.Settings.Hour_TreeOak
            .ChkHrTreePine.Checked = My.Settings.Hour_TreePine
            .ChkHrRagweed.Checked = My.Settings.Hour_Ragweed
            .ChkHrTreeSpruce.Checked = My.Settings.Hour_TreeSpruce
            .ChkHrTreeSycamore.Checked = My.Settings.Hour_TreeSycamore
            .ChkHrTreeWalnut.Checked = My.Settings.Hour_TreeWalnut
            .ChkHrTreeWillow.Checked = My.Settings.Hour_TreeWillow
            .ChkHrAqiPm10.Checked = My.Settings.Hour_Pm10
            .ChkHrAqiPm25.Checked = My.Settings.Hour_Pm25
            .ChkHrAqiO3.Checked = My.Settings.Hour_O3
            .ChkHrAqiNo2.Checked = My.Settings.Hour_No2
            .ChkHrAqiCo.Checked = My.Settings.Hour_Co
            .ChkHrAqiSo2.Checked = My.Settings.Hour_So2
            .ChkHrEpaAqi.Checked = My.Settings.Hour_EpaAqi
            .ChkHrEpaConcern.Checked = My.Settings.Hour_EpaHealthConcern
            .ChkHrEpaPollutant.Checked = My.Settings.Hour_EpaPrimaryPollutant
            .ChkHrChinaAqi.Checked = My.Settings.Hour_ChinaAqi
            .ChkHrChinaConcern.Checked = My.Settings.Hour_ChinaHealthConcern
            .ChkHrChinaPollutant.Checked = My.Settings.Hour_ChinaPrimaryPollutant
            .ChkHrRoadRisk.Checked = My.Settings.Hour_RoadRisk
            .ChkHrRiskScore.Checked = My.Settings.Hour_RiskScore
            .ChkHrRiskConfidence.Checked = My.Settings.Hour_RiskConfidence
            .ChkHrRiskCondition.Checked = My.Settings.Hour_RiskCondition
            .ChkHrHailRisk.Checked = My.Settings.Hour_HailRisk
        End With
    End Sub

    Friend Sub LoadNcSettings()
        With FrmMain
            .ChkNcBP.Checked = My.Settings.Nc_Bp
            .ChkNcDewpoint.Checked = My.Settings.Nc_Dewpoint
            .ChkNcFeelsLike.Checked = My.Settings.Nc_FeelsLike
            .ChkNcRH.Checked = My.Settings.Nc_RH
            .ChkNcPrecip.Checked = My.Settings.Nc_Precip
            .ChkNcPrecipType.Checked = My.Settings.Nc_PrecipType
            .ChkNcSunrise.Checked = My.Settings.Nc_Sunrise
            .ChkNcSunset.Checked = My.Settings.Nc_Sunset
            .ChkNcTemp.Checked = My.Settings.Nc_Temp
            .ChkNcVis.Checked = My.Settings.Nc_Vis
            .ChkNcWindDir.Checked = My.Settings.Nc_WindDir
            .ChkNcWindSpeed.Checked = My.Settings.Nc_WindSpeed
            .ChkNcWindGust.Checked = My.Settings.Nc_WindGust
            .ChkNcWxCode.Checked = My.Settings.Nc_WxCode
            .ChkNcSSR.Checked = My.Settings.Nc_SSR
            .ChkNcCloudBase.Checked = My.Settings.Nc_CloudBase
            .ChkNcCloudCeil.Checked = My.Settings.Nc_CloudCeil
            .ChkNcCloudCover.Checked = My.Settings.Nc_CloudCover
            .ChkNcTreePollen.Checked = My.Settings.Nc_TreePollen
            .ChkNcWeedPollen.Checked = My.Settings.Nc_WeedPollen
            .ChkNcGrassPollen.Checked = My.Settings.Nc_GrassPollen
            .ChkNcAcacia.Checked = My.Settings.Nc_Acacia
            .ChkNcAsh.Checked = My.Settings.Nc_Ash
            .ChkNcBeech.Checked = My.Settings.Nc_Beech
            .ChkNcBirch.Checked = My.Settings.Nc_Birch
            .ChkNcCedar.Checked = My.Settings.Nc_Cedar
            .ChkNcCottonwood.Checked = My.Settings.Nc_Cottonwood
            .ChkNcCypress.Checked = My.Settings.Nc_Cypress
            .ChkNcElder.Checked = My.Settings.Nc_Elder
            .ChkNcElm.Checked = My.Settings.Nc_Elm
            .ChkNcGrass.Checked = My.Settings.Nc_Grass
            .ChkNcHemlock.Checked = My.Settings.Nc_Hemlock
            .ChkNcHickory.Checked = My.Settings.Nc_Hickory
            .ChkNcJuniper.Checked = My.Settings.Nc_Juniper
            .ChkNcMahogany.Checked = My.Settings.Nc_Mahogany
            .ChkNcMaple.Checked = My.Settings.Nc_Maple
            .ChkNcMulberry.Checked = My.Settings.Nc_Mulberry
            .ChkNcOak.Checked = My.Settings.Nc_Oak
            .ChkNcPine.Checked = My.Settings.Nc_Pine
            .ChkNcRagweed.Checked = My.Settings.Nc_Ragweed
            .ChkNcSpruce.Checked = My.Settings.Nc_Spruce
            .ChkNcSycamore.Checked = My.Settings.Nc_Sycamore
            .ChkNcWalnut.Checked = My.Settings.Nc_Walnut
            .ChkNcWillow.Checked = My.Settings.Nc_Willow
            .ChkNcPm10.Checked = My.Settings.Nc_Pm10
            .ChkNcPm25.Checked = My.Settings.Nc_Pm25
            .ChkNcO3.Checked = My.Settings.NC_O3
            .ChkNcNo2.Checked = My.Settings.NC_No2
            .ChkNcCo.Checked = My.Settings.Nc_Co
            .ChkNcSo2.Checked = My.Settings.Nc_So2
            .ChkNcEpaAqi.Checked = My.Settings.Nc_EpaAqi
            .ChkNcEpaConcern.Checked = My.Settings.Nc_EpaHealthConcern
            .ChkNcEpaPollutant.Checked = My.Settings.NC_EpaPrimaryPollutant
            .ChkNcChinaAqi.Checked = My.Settings.NC_ChinaAqi
            .ChkNcChinaConcern.Checked = My.Settings.Nc_ChinaHealthConcern
            .ChkNcChinaPollutant.Checked = My.Settings.Nc_ChinaPrimaryPollutant
            .ChkNcRoadRisk.Checked = My.Settings.Nc_RoadRisk
            .ChkNcRiskScore.Checked = My.Settings.Nc_RiskScore
            .ChkNcRiskConfidence.Checked = My.Settings.Nc_RiskConfidence
            .ChkNcRiskCondition.Checked = My.Settings.Nc_RiskCondition
            .ChkNcHailRisk.Checked = My.Settings.Nc_HailRisk
        End With
    End Sub
    Friend Sub LoadRtSettings()
        With FrmMain
            .ChkRtCore0.Checked = My.Settings.Rt_Core0
            .ChkRtCore1.Checked = My.Settings.Rt_Core1
            .ChkRtCore2.Checked = My.Settings.Rt_Core2
            .ChkRtCore3.Checked = My.Settings.Rt_Core3
            .ChkRtCore4.Checked = My.Settings.Rt_Core4
            .ChkRtCore5.Checked = My.Settings.Rt_Core5
            .ChkRtCore6.Checked = My.Settings.Rt_Core6
            .ChkRtCore7.Checked = My.Settings.Rt_Core7
            .ChkRtCore8.Checked = My.Settings.Rt_Core8
            .ChkRtCore9.Checked = My.Settings.Rt_Core9
            .ChkRtCore10.Checked = My.Settings.Rt_Core10
            .ChkRtCore11.Checked = My.Settings.Rt_Core11
            .ChkRtCore12.Checked = My.Settings.Rt_Core12
            .ChkRtCore13.Checked = My.Settings.Rt_Core13
            .ChkRtCore14.Checked = My.Settings.Rt_Core14
            .ChkRtCore15.Checked = My.Settings.Rt_Core15
            .ChkRtCore16.Checked = My.Settings.Rt_Core16
            .ChkRtCore17.Checked = My.Settings.Rt_Core17
            .ChkRtCore18.Checked = My.Settings.Rt_Core18
            .ChkRtCore19.Checked = My.Settings.Rt_Core19
            .ChkRtCore20.Checked = My.Settings.Rt_Core20
            .ChkRtPol22.Checked = My.Settings.Rt_Pol0
            .ChkRtPol22.Checked = My.Settings.Rt_Pol1
            .ChkRtPol24.Checked = My.Settings.Rt_Pol2
            .ChkRtPol24.Checked = My.Settings.Rt_Pol3
            .ChkRtPol25.Checked = My.Settings.Rt_Pol4
            .ChkRtPol26.Checked = My.Settings.Rt_Pol5
            .ChkRtPol27.Checked = My.Settings.Rt_Pol6
            .ChkRtPol28.Checked = My.Settings.Rt_Pol7
            .ChkRtPol29.Checked = My.Settings.Rt_Pol8
            .ChkRtPol30.Checked = My.Settings.Rt_Pol9
            .ChkRtPol31.Checked = My.Settings.Rt_Pol10
            .ChkRtPol32.Checked = My.Settings.Rt_Pol11
            .ChkRtPol34.Checked = My.Settings.Rt_Pol13
            .ChkRtPol35.Checked = My.Settings.Rt_Pol14
            .ChkRtPol36.Checked = My.Settings.Rt_Pol15
            .ChkRtPol37.Checked = My.Settings.Rt_Pol16
            .ChkRtPol38.Checked = My.Settings.Rt_Pol17
            .ChkRtPol39.Checked = My.Settings.Rt_Pol18
            .ChkRtPol40.Checked = My.Settings.Rt_Pol19
            .ChkRtPol41.Checked = My.Settings.Rt_Pol20
            .ChkRtPol42.Checked = My.Settings.Rt_Pol21
            .ChkRtPol43.Checked = My.Settings.Rt_Pol22
            .ChkRtPol44.Checked = My.Settings.Rt_Pol23
            .ChkRtPol45.Checked = My.Settings.Rt_Pol24
            .ChkRtPol46.Checked = My.Settings.Rt_Pol25
        End With
    End Sub


End Module
